Milestone 5: Feature/experimental-animations + deployment
ITurres/ITurres-portfolio pull request #7
Opened 2023-05-08 17:36 UTC by ITurres

#### 🚩: Iturres-portfolio - feature/experimental-animations + deployment - >>branch<< -

> On this -Branch-, I have **Added** the succeeding **📂\* folders** and/or **📄\*\* files**:

### 📂\* src/assets/styles/animations/

- 🖼️\*\* about-stack-stack-animation.css

---

> On this -Branch-, I have **Modified** the succeeding **📂\* folders** and/or **📄\*\* files**:

### 📂\* root/

- 📄\*\* README.md

### 📂\* src/assets/styles/

- #### 📂\* animations/

  - 📄\*\* arrow-down-animation.css
  - 📄\*\* [FILE_RENAMED] nav-bar-ul-animation.css => navbar-ul-slidedown-animation.css
  - 📄\*\* about-stack-stack-animation.css

- #### 📂\* components/navbar/

  - 📄\*\* navbar.css

- #### 📂\* config/breakpoints/

  - 📄\*\* hero-section-breakpoints.css

- #### 📂\* main-stylesheets/

  - 📄\*\* index.css

- #### 📂\* page-sections/

  - 📄\*\* my-main-projects-main-section.css

---

#### 🛑Notes: \-none\-

---

#### Thank you for taking the time to review my PR ⭐!

If you need to contact me for any further details or have any questions, feel free to reach out to me on Slack as _**Arturo (Arthur) Emanuel Guerra Iturres**_.🎯

2023-05-08 17:58 UTC, Efiamotu-1 requested changes
Hi @ITurres , 

![](https://camo.githubusercontent.com/9394efa3662ade294180d682ebade56334efde7f9b0ffaf2da4786d70e86ee0c/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e6769663f6369643d65636630356534376b357561706470746730306e69646277337161787838697167737573676173776369326333756831267269643d67697068792e6769662663743d67)

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- Great job dseploying the app to github pages :100: :1st_place_medal: 
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 20:20 UTC, ITurres commented on README.md
Hi @Efiamotu-1! Thank you so much for your review! 😁, It is indeed peculiar how the images aren’t shown on your browser, I am currently testing both desktop and mobile versions of the current live demo link (based on the main -branch-) on `Chrome-Firefox-Brave`, and in all, they are shown as follows: 

![iphone-se-viewport-like](https://user-images.githubusercontent.com/100724715/236923404-7b5ed0d7-341b-47c3-b44a-06fbaa23a012.JPG)

![iphone-se-viewport-like-2](https://user-images.githubusercontent.com/100724715/236923596-cb3c2eb4-6586-4258-9793-f16c20b629fe.JPG)

![iphone-se-viewport-like-3](https://user-images.githubusercontent.com/100724715/236923679-e6b44c83-6dd6-4cdb-a62a-fa6d92f22c5c.JPG)

However, please bear in mind that the link provided on the README `file` is the old deployed version, nevertheless, this shouldn't change anything 🤔, since all the illustrations files worked since `branch` ‘Milestone 1/2/ and forth’.

Still, there could be some small differences between the final design of Figma 🕵️ and the worked one. Due to the following: 
- there is no option to export a whole image of the 2 complete illustration vectors (background included) for sections `about and contact` (there is one for the hero section tough), so I exported every `svg` illustration as individuals and placed them on a `png` background the best I could following the Figma sizes for both the desktop and mobile version, causing those -png- background -files- to have a fixed width/height.

I will be vigilant to continue with the thread 😀.

2023-05-09 01:10 UTC, Efiamotu-1 commented on README.md
@ITurres really nice pr thread, i enjoyed reading your response :grin:. I have now checked and the images are displaying on mobile version correctly :100: :1st_place_medal: , you can definitely resubmit and your next reviewer would see this thread and approve your project :+1: :sparkles: :grin:

2023-05-09 14:41 UTC, ITurres commented on README.md
Hi @Efiamotu-1! hope you are well and having a great week!🌞. Happy to know everything works as expected ☺️.  Thank you for your time and review! 💯🏅

2023-05-09 15:02 UTC, merged